// src/components/Menu.tsx
import { useState, useEffect, useCallback } from 'react'
import { Link, useNavigate } from '@tanstack/react-router'
import { getSearchPosts, type SearchPost } from '../lib/search'

type Post = SearchPost

interface MenuProps {
  isOpen: boolean
  onClose: () => void
}

export function Menu({ isOpen, onClose }: MenuProps) {
  const [isVisible, setIsVisible] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [searchResults, setSearchResults] = useState<Post[]>([])
  const [allPosts, setAllPosts] = useState<Post[]>([])
  const navigate = useNavigate()

  // Load posts for search
  useEffect(() => {
    if (isOpen && allPosts.length === 0) {
      getSearchPosts()
        .then((posts) => {
          setAllPosts(posts)
        })
        .catch(console.error)
    }
  }, [isOpen, allPosts.length])

  // Handle menu open animation
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden'
      setTimeout(() => setIsVisible(true), 50)
    } else {
      setIsVisible(false)
      document.body.style.overflow = ''
      setSearchQuery('')
      setSearchResults([])
    }
  }, [isOpen])

  // Handle escape key
  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose()
      }
    }
    document.addEventListener('keydown', handleKeydown)
    return () => document.removeEventListener('keydown', handleKeydown)
  }, [isOpen, onClose])

  // Search functionality
  const performSearch = useCallback(
    (query: string) => {
      if (!query.trim()) {
        setSearchResults([])
        return
      }

      const q = query.toLowerCase()
      const filtered = allPosts.filter((post) => {
        const title = post.title?.toLowerCase() || ''
        const description = post.description?.toLowerCase() || ''
        const tags = post.tags

        return (
          title.includes(q) ||
          description.includes(q) ||
          tags.some((tag) => tag.toLowerCase().includes(q))
        )
      })

      setSearchResults(filtered.slice(0, 10))
    },
    [allPosts]
  )

  useEffect(() => {
    performSearch(searchQuery)
  }, [searchQuery, performSearch])

  // Format date helper
  const formatDate = (dateStr: string) => {
    return new Intl.DateTimeFormat('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }).format(new Date(dateStr))
  }

  // Generate post URL
  const getPostUrl = (slug: string, pubDate: string) => {
    const date = new Date(pubDate)
    const year = date.getFullYear()
    const month = (date.getMonth() + 1).toString().padStart(2, '0')
    return `/${year}/${month}/${slug}`
  }

  const handleLinkClick = () => {
    onClose()
  }

  if (!isOpen) return null

  return (
    <div
      className={`fixed inset-0 z-50 bg-[#121212]/95 backdrop-blur-menu transition-opacity duration-500 ${
        isVisible ? 'opacity-100' : 'opacity-0'
      }`}
    >
      {/* Menu Content */}
      <div className="flex flex-col h-full" onClick={(e) => e.stopPropagation()}>
        {/* Header with Close Button */}
        <div className="flex justify-between items-center p-6 border-b border-gray-800 animate-slide-down">
          <div className="flex items-center space-x-2">
            <img
              src="/images/logo.png"
              alt="Notes by Hash Milhan"
              className="h-8 object-contain"
            />
          </div>

          <button
            onClick={onClose}
            className="w-10 h-10 flex items-center justify-center text-white hover:text-[#FF5682] transition-colors duration-200"
            aria-label="Close menu"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        {/* Menu Content Area */}
        <div className="flex-1 flex flex-col lg:flex-row">
          {/* Navigation Links */}
          <div className="flex-1 flex flex-col justify-center items-center p-8 lg:p-16">
            <nav className="text-center space-y-8">
              <Link
                to="/"
                onClick={handleLinkClick}
                className="block text-4xl lg:text-6xl font-primary text-white hover:text-[#FF5682] transition-all duration-300 animate-slide-up-1 hover:-translate-y-0.5"
              >
                Blog Home
              </Link>

              <a
                href="/about"
                onClick={handleLinkClick}
                className="block text-4xl lg:text-6xl font-primary text-white hover:text-[#FF5682] transition-all duration-300 animate-slide-up-2 hover:-translate-y-0.5"
              >
                About Hash
              </a>

              <a
                href="https://hashir.net"
                target="_blank"
                rel="noopener noreferrer"
                onClick={handleLinkClick}
                className="text-4xl lg:text-6xl font-primary text-white hover:text-[#FF5682] transition-all duration-300 flex items-center justify-center gap-4 animate-slide-up-3 hover:-translate-y-0.5"
              >
                Portfolio
                <svg
                  className="w-8 h-8 lg:w-12 lg:h-12"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                  />
                </svg>
              </a>
            </nav>
          </div>

          {/* Search Section */}
          <div className="lg:w-96 p-8 lg:p-16 border-t lg:border-t-0 lg:border-l border-gray-800 animate-slide-left flex flex-col">
            <div className="space-y-6 flex flex-col flex-1">
              <div className="relative flex-shrink-0">
                <input
                  type="text"
                  placeholder="Search..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full bg-[#2a2a2a] border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-[#a0a0a0] focus:outline-none focus:border-[#FF5682] transition-colors duration-200 font-text"
                />
                <svg
                  className="absolute right-3 top-3 w-5 h-5 text-[#a0a0a0]"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
              </div>

              {/* Search Results */}
              {searchQuery && searchResults.length > 0 && (
                <div
                  className="space-y-4 flex-1 overflow-y-auto rounded-lg bg-[#2a2a2a] p-4"
                  style={{ maxHeight: 'calc(100vh - 300px)' }}
                >
                  <h3 className="text-lg font-semibold text-white">Search Results</h3>
                  <div className="space-y-3">
                    {searchResults.map((result, index) => (
                      <Link
                        key={result.slug}
                        to={getPostUrl(result.slug, result.pubDate)}
                        onClick={handleLinkClick}
                        className="block p-4 bg-[#121212] rounded-lg hover:bg-gray-800 transition-all duration-200 animate-fade-in"
                        style={{ animationDelay: `${index * 100}ms` }}
                      >
                        <h4 className="font-medium text-white mb-1">{result.title}</h4>
                        <p className="text-sm text-[#a0a0a0] line-clamp-2">{result.description}</p>
                        <div className="flex items-center gap-2 mt-2">
                          <span className="text-xs text-[#a0a0a0]">
                            {formatDate(result.pubDate)}
                          </span>
                          <div className="flex gap-1">
                            {result.tags.slice(0, 2).map((tag) => (
                              <span
                                key={tag}
                                className="px-2 py-0.5 bg-[#121212] text-xs rounded text-[#a0a0a0]"
                              >
                                {tag}
                              </span>
                            ))}
                          </div>
                        </div>
                      </Link>
                    ))}
                  </div>
                </div>
              )}

              {/* No Results */}
              {searchQuery && searchResults.length === 0 && (
                <div className="text-[#a0a0a0] text-center py-8 flex-shrink-0">
                  No posts found matching "{searchQuery}"
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/components/Menu.vue
<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 z-50 bg-dark/95 backdrop-blur-menu transition-opacity duration-500"
    :class="{ 'opacity-100': isMenuVisible, 'opacity-0': !isMenuVisible }"
    @click="closeMenu">
    <!-- Menu Content -->
    <div class="flex flex-col h-full" @click.stop>
      <!-- Header with Close Button -->
      <div
        class="flex justify-between items-center p-6 border-b border-gray-800 animate-slide-down">
        <div class="flex items-center space-x-2">
          <div class="flex items-center">
            <img
              src="/images/logo.png"
              alt="Notes by Hash Milhan"
              class="h-8 object-contain" />
          </div>
        </div>

        <button
          @click="closeMenu"
          class="w-10 h-10 flex items-center justify-center text-white hover:text-primary transition-colors duration-200"
          aria-label="Close menu">
          <svg
            class="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Menu Content Area -->
      <div class="flex-1 flex flex-col lg:flex-row">
        <!-- Navigation Links -->
        <div
          class="flex-1 flex flex-col justify-center items-center p-8 lg:p-16">
          <nav class="text-center space-y-8">
            <a
              href="/"
              @click="closeMenu"
              class="block text-4xl lg:text-6xl font-primary text-white hover:text-accent transition-all duration-300 animate-slide-up-1">
              Blog Home
            </a>

            <a
              href="/about"
              @click="closeMenu"
              class="block text-4xl lg:text-6xl font-primary text-white hover:text-accent transition-all duration-300 animate-slide-up-2">
              About Hash
            </a>

            <a
              href="https://hashir.net"
              target="_blank"
              rel="noopener noreferrer"
              @click="closeMenu"
              class="block text-4xl lg:text-6xl font-primary text-white hover:text-accent transition-all duration-300 flex items-center justify-center gap-4 animate-slide-up-3">
              Portfolio
              <svg
                class="w-8 h-8 lg:w-12 lg:h-12"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
            </a>
          </nav>
        </div>

        <!-- Search Section -->
        <div
          class="lg:w-96 p-8 lg:p-16 border-t lg:border-t-0 lg:border-l border-gray-800 animate-slide-left flex flex-col">
          <div class="space-y-6 flex flex-col flex-1">
            <div class="relative flex-shrink-0">
              <input
                v-model="searchQuery"
                type="text"
                placeholder="Search..."
                class="w-full bg-dark-lighter border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-text-muted focus:outline-none focus:border-accent transition-colors duration-200 font-text"
                @input="performSearch" />
              <svg
                class="absolute right-3 top-3 w-5 h-5 text-text-muted"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>

            <!-- Search Results -->
            <transition-group
              name="search-results"
              tag="div"
              v-if="searchQuery && searchResults.length > 0"
              class="space-y-4 flex-1 overflow-y-auto rounded-lg bg-dark-lighter search-results-container"
              style="
                max-height: calc(100vh - 300px);
                padding: 16px 20px 16px 16px;
              ">
              <h3 key="title" class="text-lg font-semibold text-white">
                Search Results
              </h3>
              <div key="results" class="space-y-3">
                <a
                  v-for="(result, index) in searchResults"
                  :key="result.slug"
                  :href="
                    getPostUrl(
                      result.slug,
                      result.data?.pubDate || result.pubDate
                    )
                  "
                  @click="closeMenu"
                  class="block p-4 bg-dark rounded-lg hover:bg-gray-800 transition-all duration-200 animate-fade-in"
                  :style="{ animationDelay: `${index * 100}ms` }">
                  <h4 class="font-medium text-white mb-1">
                    {{ result.data?.title || result.title }}
                  </h4>
                  <p class="text-sm text-text-muted line-clamp-2">
                    {{ result.data?.description || result.description }}
                  </p>
                  <div class="flex items-center gap-2 mt-2">
                    <span class="text-xs text-text-muted">{{
                      formatDate(result.data?.pubDate || result.pubDate)
                    }}</span>
                    <div class="flex gap-1">
                      <span
                        v-for="tag in (
                          result.data?.tags ||
                          result.tags ||
                          []
                        ).slice(0, 2)"
                        :key="tag"
                        class="px-2 py-0.5 bg-dark text-xs rounded text-text-muted">
                        {{ tag }}
                      </span>
                    </div>
                  </div>
                </a>
              </div>
            </transition-group>

            <!-- No Results -->
            <transition name="no-results" mode="out-in">
              <div
                v-if="searchQuery && searchResults.length === 0"
                class="text-text-muted text-center py-8 flex-shrink-0">
                No posts found matching "{{ searchQuery }}"
              </div>
            </transition>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from "vue";

const isOpen = ref(false);
const isMenuVisible = ref(false);
const searchQuery = ref("");
const searchResults = ref<any[]>([]);
const allPosts = ref<any[]>([]);

// Menu controls
const openMenu = async () => {
  isOpen.value = true;
  document.body.style.overflow = "hidden";

  // Load posts when menu opens (in case they weren't loaded on mount)
  if (allPosts.value.length === 0) {
    await loadPosts();
  }

  // Delay to trigger enter animation
  await nextTick();
  setTimeout(() => {
    isMenuVisible.value = true;
  }, 50);
};

const closeMenu = async () => {
  isMenuVisible.value = false;
  document.body.style.overflow = "";
  searchQuery.value = "";
  searchResults.value = [];

  // Wait for exit animation before hiding
  setTimeout(() => {
    isOpen.value = false;
  }, 300);
};

// Load posts for search
const loadPosts = async () => {
  try {
    const response = await fetch("/api/search.json");

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    // Handle both response formats: array or object with posts property
    let posts = [];
    if (Array.isArray(data)) {
      posts = data;
    } else if (data.posts && Array.isArray(data.posts)) {
      posts = data.posts;
    }

    allPosts.value = posts;
  } catch (error) {
    console.error("Failed to load posts for search:", error);
  }
};

// Search functionality
const performSearch = async () => {
  if (!searchQuery.value.trim()) {
    searchResults.value = [];
    return;
  }

  const query = searchQuery.value.toLowerCase();
  const filteredResults = allPosts.value.filter((post) => {
    // More robust data access
    const title = post?.data?.title || post?.title || "";
    const description = post?.data?.description || post?.description || "";
    const tags = post?.data?.tags || post?.tags || [];
    const body = post?.body || "";

    const titleMatch = title.toLowerCase().includes(query);
    const descriptionMatch = description.toLowerCase().includes(query);
    const tagsMatch =
      Array.isArray(tags) &&
      tags.some((tag: string) => tag.toLowerCase().includes(query));
    const contentMatch = body && body.toLowerCase().includes(query);

    return titleMatch || descriptionMatch || tagsMatch || contentMatch;
  });

  searchResults.value = filteredResults.slice(0, 10);
};

// Format date helper
const formatDate = (date: string | Date) => {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(new Date(date));
};

// Generate post URL in format /yyyy/mm/slug
const getPostUrl = (slug: string, pubDate: string | Date): string => {
  const date = new Date(pubDate);
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  return `/${year}/${month}/${slug}`;
};

// Event listeners
const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === "Escape" && isOpen.value) {
    closeMenu();
  }
};

onMounted(() => {
  document.addEventListener("toggle-menu", openMenu);
  document.addEventListener("keydown", handleKeydown);
  loadPosts();
});

onUnmounted(() => {
  document.removeEventListener("toggle-menu", openMenu);
  document.removeEventListener("keydown", handleKeydown);
  document.body.style.overflow = "";
});
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

/* Staggered slide-up animations for navigation links */
@keyframes slideUpFade {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes slideLeft {
  from {
    opacity: 0;
    transform: translateX(30px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.animate-slide-up-1 {
  animation: slideUpFade 0.6s ease-out 0.2s both;
}

.animate-slide-up-2 {
  animation: slideUpFade 0.6s ease-out 0.4s both;
}

.animate-slide-up-3 {
  animation: slideUpFade 0.6s ease-out 0.6s both;
}

.animate-slide-down {
  animation: slideDown 0.5s ease-out 0.1s both;
}

.animate-slide-left {
  animation: slideLeft 0.6s ease-out 0.3s both;
}

.animate-fade-in {
  animation: fadeIn 0.4s ease-out both;
}

/* Transition groups for search results */
.search-results-enter-active {
  transition: all 0.3s ease-out;
}

.search-results-leave-active {
  transition: all 0.2s ease-in;
}

.search-results-enter-from {
  opacity: 0;
  transform: translateY(10px);
}

.search-results-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

.no-results-enter-active,
.no-results-leave-active {
  transition: all 0.3s ease;
}

.no-results-enter-from,
.no-results-leave-to {
  opacity: 0;
  transform: translateY(10px);
}

/* Hover effects */
nav a:hover {
  transform: translateY(-2px);
}

/* Custom scrollbar for search results */
.search-results-container::-webkit-scrollbar {
  width: 6px;
}

.search-results-container::-webkit-scrollbar-track {
  background: transparent;
  margin: 8px 4px;
}

.search-results-container::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.15);
  border-radius: 3px;
  border: 1px solid transparent;
  background-clip: content-box;
}

.search-results-container::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.25);
  background-clip: content-box;
}
</style>
